services:
  # A Docker web service
  - type: web
    name: socket.io-Server
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x app/main.py